//
//  AssetManager.swift
//  BackgroundAssetDemo
//
//  Created by Itsuki on 2026/09/06.
//

import BackgroundAssets
import SwiftUI
import System

@Observable
class AssetManager {
    private let manager = AssetPackManager.shared

    // My preferred Asset Folder structure
    // ```
    // AssetRoot
    // ├── Manifest.json
    // ├── src
    // │   └── ...other asset files.
    // └── tree.json (folder structure generated by the `tree` command: `tree src -J > tree.json`)
    // ```
    // Reason: Allow us to get contents within the `src` folder without having to hard code all file paths.

    // same as the one defined in Manifest.json of the asset pack.
    private let assetIds = ["itsuki.enjoy.BackgroundAssetDemo.asset.1"]
    // same as the directory passed to fileSelectors in Manifest.json of the asset pack.
    // assuming that you have the same folder for all asset packs
    private let assetFolder = "src"
    // assuming that there is a tree.json (from the `tree` command) at the asset directory root
    private let assetFolderStructureTreeFile = "tree.json"

    private(set) var assetPacks: Set<AssetPack> = []

    var error: Swift.Error?

    init() {
        initializeAssetPacks()
    }

    private func initializeAssetPacks() {
        print(#function)
        Task {
            do {
                // To get a assetPack with a specific ID: use assetPack(withID:)
                // To get a subset of asset packs that best match a specific language: use localizedAssetPacks(for:) or localizedAssetPacks for best matches over the current preferred languages
                self.assetPacks = try await self.manager.manifest.assetPacks
                    .filter({ self.assetIds.contains($0.id) })
            } catch {
                print("Error loading asset pack: \(error)")
                self.error = error
            }
        }
    }

    // MARK: - Download/Remove asset packs if necessary
    // Download asset pack if necessary
    func downloadAssetPack(id: String, requiresLatestVersion: Bool) async {
        print(#function)
        do {
            guard let assetPack = self.assetPacks.first(where: { $0.id == id })
            else {
                throw ManagedBackgroundAssetsError.assetPackNotFound(withID: id)
            }
            // `ensureLocalAvailability`: ensure that the system downloads an asset pack
            // - If the system previously downloaded the asset pack, the ensureLocalAvailability(of:) method returns quickly without downloading it again.
            // - For an asset pack with an essential or a prefetch download policy, the system may finish downloading the asset pack before you call this method. (Even for an asset pack with an essential download policy, network dropouts or other uncommon issues can prevent the system from downloading it until we call the ensureLocalAvailability(of:) method.)
            // - To download an asset pack with an on-demand download policy, this method initiates the download and waits for it to finish before returning.
            // - If this method returns without throwing an error, the asset pack is available to access locally.
            try await self.manager
                .ensureLocalAvailability(
                    of: [assetPack],
                    requireLatestVersions: requiresLatestVersion
                )
        } catch {
            print("Error loading asset pack: \(error)")
            self.error = error
        }
    }

    // Remove a downloaded asset pack data (does NOT remove anything from the server)
    // To redownload an asset pack, call the ensureLocalAvailability(of:) method again.
    // Call this method, for example, when we are done with using an asset pack to free up storage space on the device.
    func removeAssetPack(id: String) async {
        print(#function)
        do {
            try await self.manager.remove(assetPackWithID: id)
        } catch {
            print("Error removing asset pack: \(error)")
            self.error = error
        }
    }

    // MARK: - show / cancel download progress
    // Get download status of an asset pack.
    func downloadStatus(for assetId: AssetPack.ID) -> some Sendable
        & AsyncSequence<AssetPackManager.DownloadStatusUpdate, Never>
    {
        print(#function)
        let downloadStatus = manager.statusUpdates(
            forAssetPackWithID: assetId
        )
        // to cancel a download
        // call the cancel() method on the Progress objects as shown in the view
        // ie:
        // ```
        // guard case .downloading(let assetPack, let progress) = downloadStatus,
        //      assetPack.id == id
        //      else { return }
        // progress.cancel()
        // ```

        return downloadStatus
    }

    // Get asset pack status.
    // 1. neither localStatus nor status trigger any downloads, updates, or removals
    // 2. Generally, we shouldn’t need to handle situations such as outOfDate, updateAvailable, and etc explicitly because the system automatically polls for updates periodically in the background.
    func assetPackStatus(for id: AssetPack.ID, localOnly: Bool) async
        -> AssetPack.Status?
    {
        print(#function)
        do {
            guard let assetPack = self.assetPacks.first(where: { $0.id == id })
            else {
                throw ManagedBackgroundAssetsError.assetPackNotFound(withID: id)
            }

            if localOnly {
                // Checks an asset pack’s *local* status
                // This method checks only status values that are determinable offline. ie: outOfDate (in some situations), obsolete (in some situations), downloaded.
                // It doesn’t induce any network traffic or automatically trigger any downloads, updates, or removals.
                // Because this method doesn’t communicate with the server, it can’t determine whether a particular asset pack exists in the first place. Instead, it returns an empty status value when provided a nonexistent asset-pack ID, which is indistinguishable from the situation in which the asset pack does indeed exist but hasn’t yet been downloaded
                return await self.manager.localStatus(ofAssetPackWithID: id)
            }

            return try await self.manager.status(relativeTo: assetPack)

        } catch {
            print("Error getting asset pack status: \(error)")
            return nil
        }
    }

    // MARK: - Load asset pack contents
    // Get the content of a specific file within a specific asset
    func loadDataFromAsset(
        _ assetId: String,
        filePath: String
    ) async -> Data? {
        print(#function)
        do {
            let filePath = FilePath(filePath)
            let data = try self.manager.contents(
                at: filePath
            )
            return data
        } catch {
            print("Error loading contents from asset pack: \(error)")
            self.error = error
            return nil
        }
    }

    // Get the asset pack folder structure.
    // assuming that there is a tree.json (from the `tree` command) at the asset directory root
    func loadAssetContentStructure(_ assetId: String) async -> [TreeJsonEntry] {
        guard
            let data = await self.loadDataFromAsset(
                assetId,
                filePath: assetFolderStructureTreeFile
            )
        else {
            return []
        }

        let decoder = JSONDecoder()
        do {
            let tree = try decoder.decode([TreeJsonEntry].self, from: data)
            print(tree)
            return tree
        } catch {
            print("Error decoding asset content structure: \(error)")
            self.error = error
            return []
        }
    }

    // MARK: - Manual Asset pack Updates
    private func checkForUpdates() async {
        print(#function)
        do {
            // Gets the latest asset-pack information from the server, updates outdated asset packs, and removes obsolete asset packs.
            // NOTE: the system will automatically handle any downloads/updates/removals and therefore calling this method periodically shouldn't be necessary.
            let updates = try await self.manager.checkForUpdates()
            self.assetPacks = self.assetPacks.filter({
                updates.removedIDs.contains($0.id)
            })
        } catch {
            print("Error checking for updates: \(error)")
            self.error = error
        }
    }
}

enum TreeJsonEntry: Decodable, Hashable {
    case directory(name: String, contents: [TreeJsonEntry])
    case file(name: String)
    case report

    enum CodingKeys: CodingKey {
        case type
        case name
        case contents
    }

    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)

        switch type {
        case "directory":
            let name = try container.decode(String.self, forKey: .name)
            let contents = try container.decodeIfPresent(
                [TreeJsonEntry].self,
                forKey: .contents
            )
            self = .directory(name: name, contents: contents ?? [])
        case "file":
            let name = try container.decode(String.self, forKey: .name)
            self = .file(name: name)
        case "report":
            self = .report
        default:
            throw DecodingError.dataCorruptedError(
                forKey: CodingKeys.type,
                in: container,
                debugDescription: "Invalid type: \(type)"
            )
        }
    }
}
